DESIGN_NAME: rvx
VERILOG_FILES: 
  - dir::rvx.v
  - dir::rvx_bus.v
  - dir::rvx_core.v
  - dir::rvx_gpio.v
  - dir::rvx_mtimer.v
  - dir::rvx_spi.v
  - dir::rvx_uart.v
CLOCK_PORT: clock
CLOCK_PERIOD: 20.0

