DESIGN_NAME: rvx
VERILOG_FILES: 
  - dir::rvx.v
  - dir::rvx_bus.v
  - dir::rvx_core.v
  - dir::rvx_gpio.v
  - dir::rvx_mtimer.v
  - dir::rvx_spi.v
  - dir::rvx_uart.v
CLOCK_PORT: clock
CLOCK_PERIOD: 20.0
EXTRA_LEFS:
  - dir::runs/ram_macro/results/final/lef/rvx_ram.lef
EXTRA_LIBS:
  - dir::runs/ram_macro/results/final/lib/rvx_ram.lib
EXTRA_GDS_FILES:
  - dir::runs/ram_macro/results/final/gds/rvx_ram.gds
FP_PDN_MACRO_HOOKS: "rvx_ram_instance vdd vss vdd vss"
